**Preparing the data**


In [1]:
import numpy as np
from tensorflow.keras import datasets, utils

In [8]:
(x_train, y_train), (x_test, y_test) = datasets.cifar10.load_data()

In [9]:
# Visualizing the data for one row of one image - it is essentially a set of pixels on the RGB color scheme

# Note that the format of the data is [50000, 32, 32, 3] meaning there are 50,000 images each in a 32x32 matrix with 3 values (RGB)
# This is a 4 dimensional tensor
x_train[0][0]

array([[ 59,  62,  63],
       [ 43,  46,  45],
       [ 50,  48,  43],
       [ 68,  54,  42],
       [ 98,  73,  52],
       [119,  91,  63],
       [139, 107,  75],
       [145, 110,  80],
       [149, 117,  89],
       [149, 120,  93],
       [131, 103,  77],
       [125,  99,  76],
       [142, 115,  91],
       [144, 112,  86],
       [137, 105,  79],
       [129,  97,  71],
       [137, 106,  79],
       [134, 106,  76],
       [124,  97,  64],
       [139, 113,  78],
       [139, 112,  75],
       [133, 105,  69],
       [136, 105,  74],
       [139, 108,  77],
       [152, 120,  89],
       [163, 131, 100],
       [168, 136, 108],
       [159, 129, 102],
       [158, 130, 104],
       [158, 132, 108],
       [152, 125, 102],
       [148, 124, 103]], dtype=uint8)

In [10]:
# Scale each image, so that it lies between 0 and 1 (currently up to 255 for the RGB color scheme)
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

# Visualizing the scaled data
x_train[0][0]

array([[0.23137255, 0.24313726, 0.24705882],
       [0.16862746, 0.18039216, 0.1764706 ],
       [0.19607843, 0.1882353 , 0.16862746],
       [0.26666668, 0.21176471, 0.16470589],
       [0.38431373, 0.28627452, 0.20392157],
       [0.46666667, 0.35686275, 0.24705882],
       [0.54509807, 0.41960785, 0.29411766],
       [0.5686275 , 0.43137255, 0.3137255 ],
       [0.58431375, 0.45882353, 0.34901962],
       [0.58431375, 0.47058824, 0.3647059 ],
       [0.5137255 , 0.40392157, 0.3019608 ],
       [0.49019608, 0.3882353 , 0.29803923],
       [0.5568628 , 0.4509804 , 0.35686275],
       [0.5647059 , 0.4392157 , 0.3372549 ],
       [0.5372549 , 0.4117647 , 0.30980393],
       [0.5058824 , 0.38039216, 0.2784314 ],
       [0.5372549 , 0.41568628, 0.30980393],
       [0.5254902 , 0.41568628, 0.29803923],
       [0.4862745 , 0.38039216, 0.2509804 ],
       [0.54509807, 0.44313726, 0.30588236],
       [0.54509807, 0.4392157 , 0.29411766],
       [0.52156866, 0.4117647 , 0.27058825],
       [0.

In [13]:
# Y data includes the "correct categories", known as the "labels"
y_test

array([[3],
       [8],
       [8],
       ...,
       [5],
       [1],
       [7]], dtype=uint8)

In [14]:
# Here we one-hot-encode the labels (which means creating an 10-element array, and putting a 1 based on the digit)
# For example, the second row is in the 8th position (from 0 to 9)

NUM_CLASSES = 10
y_train = utils.to_categorical(y_train, NUM_CLASSES)
y_test = utils.to_categorical(y_test, NUM_CLASSES)

y_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]], dtype=float32)

In [19]:
x_train.shape

(50000, 32, 32, 3)

## Building the model

In [21]:
from tensorflow.keras import layers, models

# A sequential model is useful for defining a linear stack of layers (where one layer goes directly into the next layer)
# We'll build a sequential model for this example - here we are just defining the model, not fitting it to any data
model = models.Sequential([
    layers.Flatten(input_shape=(32, 32, 3)),
    layers.Dense(200, activation='relu'),
    layers.Dense(150, activation='relu'),
    layers.Dense(10, activation='softmax')
])

In [38]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 3072)              0         
                                                                 
 dense (Dense)               (None, 200)               614600    
                                                                 
 dense_1 (Dense)             (None, 150)               30150     
                                                                 
 dense_2 (Dense)             (None, 10)                1510      
                                                                 
Total params: 646260 (2.47 MB)
Trainable params: 646260 (2.47 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [22]:
# This is another way to structure the model definition using the functional API
input_layer = layers.Input(shape=(32, 32, 3))
x = layers.Flatten()(input_layer)
x = layers.Dense(units=200, activation='relu')(x)
x = layers.Dense(units=150, activation='relu')(x)
output_layer = layers.Dense(units=10, activation='softmax')(x)
model_second = models.Model(input_layer, output_layer)

In [23]:
from tensorflow.keras import optimizers

opt = optimizers.Adam(learning_rate=0.0005)
model.compile(loss='categorical_crossentropy', optimizer = opt, metrics=['accuracy'])

In [24]:
model.fit(x_train,
          y_train,
          batch_size = 32,
          epochs = 10,
          shuffle = True)

Epoch 1/10
1563/1563 [==============================] - 18s 11ms/step - loss: 1.8503 - accuracy: 0.3340
Epoch 2/10
1563/1563 [==============================] - 17s 11ms/step - loss: 1.6668 - accuracy: 0.4035
Epoch 3/10
1563/1563 [==============================] - 16s 10ms/step - loss: 1.5898 - accuracy: 0.4312
Epoch 4/10
1563/1563 [==============================] - 22s 14ms/step - loss: 1.5348 - accuracy: 0.4524
Epoch 5/10
1563/1563 [==============================] - 19s 12ms/step - loss: 1.4979 - accuracy: 0.4642
Epoch 6/10
1563/1563 [==============================] - 22s 14ms/step - loss: 1.4686 - accuracy: 0.4791
Epoch 7/10
1563/1563 [==============================] - 21s 13ms/step - loss: 1.4373 - accuracy: 0.4854
Epoch 8/10
1563/1563 [==============================] - 24s 15ms/step - loss: 1.4116 - accuracy: 0.4962
Epoch 9/10
1563/1563 [==============================] - 22s 14ms/step - loss: 1.3930 - accuracy: 0.5040
Epoch 10/10
1563/1563 [==============================] - 23s 15m

In [25]:
model.evaluate(x_test, y_test)

313/313 [==============================] - 2s 5ms/step - loss: 1.4309 - accuracy: 0.4944


[1.4309005737304688, 0.4943999946117401]

In [26]:
CLASSES = np.array(['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck'])

preds = model.predict(x_test)
preds_single = CLASSES[np.argmax(preds, axis = -1)]
actual_single = CLASSES[np.argmax(y_test, axis = -1)]

313/313 [==============================] - 1s 3ms/step


In [34]:
import matplotlib.pyplot as plt
n_to_show = 10
indices = np.random.choice(range(len(x_test)), n_to_show)

fig = plt.figure(figsize=(15, 3))
fig.subplots_adjust(hspace=0.4, wspace=0.4)

<Figure size 1500x300 with 0 Axes>

In [36]:
for i, idx in enumerate(indices):
    img = x_test[idx]
    ax = fig.add_subplot(1, n_to_show, i+1)
    ax.axis('off')
    ax.text(0.5, -0.35, 'pred = ' + str(preds_single[idx]), fontsize=10, ha='center', transform=ax.transAxes)
    ax.text(0.5, -0.7, 'actual = ' + str(actual_single[idx]), fontsize=10, ha='center', transform=ax.transAxes)
    ax.imshow(img)

plt.tight_layout()
plt.savefig("output_image.png", dpi=300)
plt.close()

In [32]:
plt.show()